package com.unbank.mybatis.dao;

import com.unbank.mybatis.entity.QgydData;
import com.unbank.mybatis.entity.QgydDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QgydDataMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int countByExample(QgydDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int deleteByExample(QgydDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int insert(QgydData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int insertSelective(QgydData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	List<QgydData> selectByExampleWithBLOBs(QgydDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	List<QgydData> selectByExample(QgydDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	QgydData selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int updateByExampleSelective(@Param("record") QgydData record,
			@Param("example") QgydDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") QgydData record,
			@Param("example") QgydDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int updateByExample(@Param("record") QgydData record,
			@Param("example") QgydDataExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int updateByPrimaryKeySelective(QgydData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(QgydData record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	int updateByPrimaryKey(QgydData record);
}