package com.unbank.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class QgydDataExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public QgydDataExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(String value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(String value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(String value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(String value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(String value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(String value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLike(String value) {
			addCriterion("time like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotLike(String value) {
			addCriterion("time not like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<String> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<String> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(String value1, String value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(String value1, String value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andCategoryidIsNull() {
			addCriterion("categoryid is null");
			return (Criteria) this;
		}

		public Criteria andCategoryidIsNotNull() {
			addCriterion("categoryid is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryidEqualTo(String value) {
			addCriterion("categoryid =", value, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidNotEqualTo(String value) {
			addCriterion("categoryid <>", value, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidGreaterThan(String value) {
			addCriterion("categoryid >", value, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidGreaterThanOrEqualTo(String value) {
			addCriterion("categoryid >=", value, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidLessThan(String value) {
			addCriterion("categoryid <", value, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidLessThanOrEqualTo(String value) {
			addCriterion("categoryid <=", value, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidLike(String value) {
			addCriterion("categoryid like", value, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidNotLike(String value) {
			addCriterion("categoryid not like", value, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidIn(List<String> values) {
			addCriterion("categoryid in", values, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidNotIn(List<String> values) {
			addCriterion("categoryid not in", values, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidBetween(String value1, String value2) {
			addCriterion("categoryid between", value1, value2, "categoryid");
			return (Criteria) this;
		}

		public Criteria andCategoryidNotBetween(String value1, String value2) {
			addCriterion("categoryid not between", value1, value2, "categoryid");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailIsNull() {
			addCriterion("hgydDeatail is null");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailIsNotNull() {
			addCriterion("hgydDeatail is not null");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailEqualTo(String value) {
			addCriterion("hgydDeatail =", value, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailNotEqualTo(String value) {
			addCriterion("hgydDeatail <>", value, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailGreaterThan(String value) {
			addCriterion("hgydDeatail >", value, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailGreaterThanOrEqualTo(String value) {
			addCriterion("hgydDeatail >=", value, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailLessThan(String value) {
			addCriterion("hgydDeatail <", value, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailLessThanOrEqualTo(String value) {
			addCriterion("hgydDeatail <=", value, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailLike(String value) {
			addCriterion("hgydDeatail like", value, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailNotLike(String value) {
			addCriterion("hgydDeatail not like", value, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailIn(List<String> values) {
			addCriterion("hgydDeatail in", values, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailNotIn(List<String> values) {
			addCriterion("hgydDeatail not in", values, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailBetween(String value1, String value2) {
			addCriterion("hgydDeatail between", value1, value2, "hgyddeatail");
			return (Criteria) this;
		}

		public Criteria andHgyddeatailNotBetween(String value1, String value2) {
			addCriterion("hgydDeatail not between", value1, value2,
					"hgyddeatail");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table qgyd_data
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qgyd_data
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 25 11:23:19 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}