package com.unbank.mybatis.entity;

public class QgydData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qgyd_data.id
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qgyd_data.time
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	private String time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qgyd_data.categoryid
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	private String categoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qgyd_data.hgydDeatail
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	private String hgyddeatail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qgyd_data.text
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	private String text;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qgyd_data.id
	 * @return  the value of qgyd_data.id
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qgyd_data.id
	 * @param id  the value for qgyd_data.id
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qgyd_data.time
	 * @return  the value of qgyd_data.time
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qgyd_data.time
	 * @param time  the value for qgyd_data.time
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qgyd_data.categoryid
	 * @return  the value of qgyd_data.categoryid
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public String getCategoryid() {
		return categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qgyd_data.categoryid
	 * @param categoryid  the value for qgyd_data.categoryid
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public void setCategoryid(String categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qgyd_data.hgydDeatail
	 * @return  the value of qgyd_data.hgydDeatail
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public String getHgyddeatail() {
		return hgyddeatail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qgyd_data.hgydDeatail
	 * @param hgyddeatail  the value for qgyd_data.hgydDeatail
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public void setHgyddeatail(String hgyddeatail) {
		this.hgyddeatail = hgyddeatail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qgyd_data.text
	 * @return  the value of qgyd_data.text
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qgyd_data.text
	 * @param text  the value for qgyd_data.text
	 * @mbggenerated  Mon Jul 25 14:15:02 CST 2016
	 */
	public void setText(String text) {
		this.text = text;
	}
}